
const SET_ACCOUNT = 'SET_ACCOUNT'
const SET_ISCONNECTED = 'SET_ISCONNECTED'
const SET_CHAINID = 'SET_CHAINID'
const SET_DRIZZLE = 'SET_DRIZZLE'
export {
  SET_ACCOUNT,
  SET_ISCONNECTED,
  SET_CHAINID,
  SET_DRIZZLE
}
