
const SET_ACCOUNT = 'SET_ACCOUNT'
const SET_ISCONNECTED = 'SET_ISCONNECTED'
const SET_CHAINID = 'SET_CHAINID'
const SET_DRIZZLE = 'SET_DRIZZLE'
const SET_ACCOUNTADDR = 'SET_ACCOUNTADDR'
const GET_MYCATINFOS = 'GET_MYCATINFOS'
const GET_TRADEMARKETINFO = 'GET_TRADEMARKETINFO'
export {
  SET_ACCOUNT,
  SET_ISCONNECTED,
  SET_CHAINID,
  SET_DRIZZLE,
  SET_ACCOUNTADDR,
  GET_MYCATINFOS,
  GET_TRADEMARKETINFO
}
